layout_spectrum: 0.5558539
color:
  saturation: 0.6748286
  lightness: 0.8772376
  brandStrength: 0.7814178
  brandColors:
    - '#020103'
    - '#645466'
    - '#888889'
    - '#FFFFFD'
    - '#7F170E'
  rhythmicContrast: 0.9541826
typography_spectrum: 0.09505906
name: Know Projects
