layout_spectrum: 0.5558539
typography_spectrum: 0.09505906
color:
  saturation: 0.6748286
  lightness: 0.8772376
  brandStrength: 0.7814178
  brandColors:
    - '#303030'
    - '#E0E0E0'
    - '#5C5C5C'
    - '#A3A3A3'
  rhythmicContrast: 0.9541826
name: Know Projects
